os:
  - linux
  - mac

sudo: required

language:
  - go

go:
  1.12.x

notifications:
  gitter:
    on_success: always
    on_failure: always
  email: truemac

before_script:
  - go get -u ./...
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.18.0
  - echo "checking linting in golang ..."
  - golangci-lint run
  - echo "perfect linting standards! moving ahead ..."
  - echo "checking go format ..."
  - diff -u <(echo -n) <(gofmt -d ./src ./tsdb)
  - echo "perfect go format. moving ahead ..."

script:
  - make build
  - make test
  - make test_complete
